# Homebrew

# Tap
tap "qmk/qmk"

# Formula
brew "avrdude"       # keyball等のAVRキーボードファームウェア書き込みに使用
brew "fish"
brew "gh"
brew "git"
brew "gogcli"
brew "bash"
brew "hasura-cli"
brew "jq"
brew "herdr"
brew "k6"
brew "pandoc"
brew "sheldon"
brew "zsh"
brew "git-flow"
brew "mas"
brew "mise"
brew "starship"
brew "tmux"
brew "tree"
brew "vim"
brew "qmk/qmk/qmk"

# Cask
cask "adobe-acrobat-reader"
cask "alacritty"
cask "alt-tab"
cask "android-studio"
cask "antigravity"
cask "antigravity-cli"
cask "apidog"
cask "appcleaner"
cask "arc"
cask "biscuit"
cask "bitwarden"
cask "brave-browser"
cask "chatgpt"
cask "claude"
cask "claude-code"
cask "clipy"
cask "cursor"
cask "dbeaver-community"
cask "ddpm"
cask "deepl"
cask "devin-desktop"
cask "devtoys"
cask "discord"
cask "displaylink"
cask "docker-desktop"
cask "drawio"
cask "figma"
cask "font-fira-code-nerd-font"
cask "font-ricty-diminished"
cask "gimp"
cask "google-chrome"
cask "google-drive"
cask "google-japanese-ime"
cask "hhkb"
cask "homerow"
cask "inkscape"
cask "iterm2"
cask "itsycal"
cask "karabiner-elements"
cask "kiro"
cask "kiro-cli"
cask "meetingbar"
cask "mi"
cask "microsoft-edge"
cask "microsoft-onenote"
cask "mongodb-compass"
cask "mos"
cask "notion"
cask "notion-calendar"
cask "obsidian"
cask "postman"
cask "qmk-toolbox"
cask "raycast"
cask "send-anywhere"
cask "session-manager-plugin"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "utm"
cask "visual-studio-code"
cask "warp"
cask "wireshark-app"
cask "zen"
cask "zoom"

# Mas
mas "Goodnotes", id: 1444383602
mas "Hidden Bar", id: 1452453066
mas "HiddenMe", id: 467040476
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "MenubarX", id: 1575588022
mas "RunCat Neo", id: 6757801838
mas "Xcode", id: 497799835
