[tools]
claude-code = "latest"
gemini-cli = "latest"
node = "24.15.0"
pnpm = "11.0.4"
github-cli = "latest"
aws = "2.33.22"
dotnet = "8.0.410"
python = "3.13.3"
mysql = "8.0.33"
yarn = "4.1.1"
bun = "latest"
k6 = "latest"
hasura-cli = "2.48.13"
terraform = "1.14.7"
tflint = "0.59.1"
terraform-docs = "0.20.0"
terragrunt = "0.93.0"
